services:
  database:
    container_name: database
    image: mrkustoff/db-image
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - base-network
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file: .env
    volumes:
      - postgressData:/var/lib/postgresql/data
      - postgressLogs:/var/log/postgresql
    platform: linux/arm64/v8
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: api
    image: mrkustoff/nest-app-image
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: unless-stopped
    networks:
      - base-network
    volumes:
      - ./src:/app/src/
      - ./node_modules:/app/node_modules/
    depends_on:
      - database

volumes:
  postgressData:
  postgressLogs:

networks:
  base-network:
    name: base-network
    driver: bridge
